version: "3.9"
services:
  db:
    image: 'postgres:15.1-alpine'
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
